### ISSUE TITLE
Problem in 3 beta release

### ISSUE THREAD

**Issue by mahdiit** [couchbaselabs/couchbase-aspnet#90]
i update my couchbase server from 4 to 5,
so i update project sdk to version 3-beta .net client and also couchbase asp.net cache 

but there was error in Common.Loging.Core package, it missing one dependency 
i search but can not find any workaround for this  problem, 

seems problem reported here 
https://github.com/net-commons/common-logging/issues/172

**Comment by MikeGoldsmith** [comment]
Hi @mahdiit - thanks for the bug report and for linking your investigation work. We'll look into it and monitor the issue you linked to.

**Comment by jeffrymorris** [comment]
@mahdiit -

What .NET version are you using?

-Jeff

**Comment by mahdiit** [comment]
.net 4.6.2

**Comment by jeffrymorris** [comment]
@mahdiit -

I was able to get up and running with .net 4.5.2 yesterday. The major change is the version change of Common.Logging.Log4Net1213 to Common.Logging.Log4Net207 in the Couchbase .NET SDK. Here is the ticket [NCBC-1655](https://issues.couchbase.com/browse/NCBC-1655). 

The fix is to change the log4net dependency to Common.Logging.Log4Net207 using NuGet and then to update the Web.Config to use the correct version of log4net:

```XML
<common>
    <logging>
      <factoryAdapter type="Common.Logging.Log4Net.Log4NetLoggerFactoryAdapter, Common.Logging.Log4Net207">
        <arg key="configType" value="INLINE" />
      </factoryAdapter>
    </logging>
  </common>
```
Let me know if that works for you.

-Jeff

**Comment by jeffrymorris** [comment]
@mahdiit -

Please provide some feedback here; if not I'll close the issue.

Jeff

**Comment by mahdiit** [comment]
@jeffrymorris 

thank you from workground, 
but it is impossible for me to test and say the result in short time,
because of side effect of update couchbase from v4 to v5 and then update all assembly in my project.

so you can close this issue. 

Thanks jeff

**Comment by jeffrymorris** [comment]
@mahdiit 

Sounds good, ping me if you need me to reopen it or if you encounter any other problems.

Jeff
